
platform :ios, ’9.0’

inhibit_all_warnings!

use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'


target 'papa' do
    pod 'Masonry', '~> 1.1.0'
    pod 'YYModel', '~> 1.0.4'
    pod 'AFNetworking', '~> 3.2.1'
end


